participants:

    Solid:
        interfaces:
        - nodes-mesh: Solid-Mesh-Ala
          patch: surfaceAla
          read-data: [ForceAla]
          write-data: [DisplacementAla]
        - nodes-mesh: Solid-Mesh-Varilla
          patch: surfaceVarilla
          write-data: [DisplacementVarilla]  
          
precice-config-file: ../precice-config.xml
